//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_de_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int id_inventario { get; set; }
        public Nullable<int> inv_articulo { get; set; }
        public Nullable<int> inv_cantidad { get; set; }
        public Nullable<int> inv_cantidad_min { get; set; }
        public string inv_descripcion { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
