//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_de_Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Control_de_InventarioEntities : DbContext
    {
        public Control_de_InventarioEntities()
            : base("name=Control_de_InventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Detalle_Venta> Detalle_Venta { get; set; }
        public virtual DbSet<Entreda> Entreda { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<vwmostrarusuarios> vwmostrarusuarios { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<vwmostrarinventario> vwmostrarinventario { get; set; }
        public virtual DbSet<vwmostrararticulo> vwmostrararticulo { get; set; }
        public virtual DbSet<vwmostrarentrada> vwmostrarentrada { get; set; }
    
        public virtual int spAgregarDetalleVenta(Nullable<int> deta_id_detalle_venta, Nullable<int> deta_id_articulo, Nullable<decimal> deta_precio_uni, Nullable<int> deta_cantidad)
        {
            var deta_id_detalle_ventaParameter = deta_id_detalle_venta.HasValue ?
                new ObjectParameter("deta_id_detalle_venta", deta_id_detalle_venta) :
                new ObjectParameter("deta_id_detalle_venta", typeof(int));
    
            var deta_id_articuloParameter = deta_id_articulo.HasValue ?
                new ObjectParameter("deta_id_articulo", deta_id_articulo) :
                new ObjectParameter("deta_id_articulo", typeof(int));
    
            var deta_precio_uniParameter = deta_precio_uni.HasValue ?
                new ObjectParameter("deta_precio_uni", deta_precio_uni) :
                new ObjectParameter("deta_precio_uni", typeof(decimal));
    
            var deta_cantidadParameter = deta_cantidad.HasValue ?
                new ObjectParameter("deta_cantidad", deta_cantidad) :
                new ObjectParameter("deta_cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarDetalleVenta", deta_id_detalle_ventaParameter, deta_id_articuloParameter, deta_precio_uniParameter, deta_cantidadParameter);
        }
    
        public virtual int spAgregarVenta(Nullable<int> ven_id_usuario, Nullable<decimal> ven_total)
        {
            var ven_id_usuarioParameter = ven_id_usuario.HasValue ?
                new ObjectParameter("ven_id_usuario", ven_id_usuario) :
                new ObjectParameter("ven_id_usuario", typeof(int));
    
            var ven_totalParameter = ven_total.HasValue ?
                new ObjectParameter("ven_total", ven_total) :
                new ObjectParameter("ven_total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarVenta", ven_id_usuarioParameter, ven_totalParameter);
        }
    
        public virtual int spInventarioSalida(Nullable<int> inv_articulo, Nullable<int> inv_descontar_cantidad)
        {
            var inv_articuloParameter = inv_articulo.HasValue ?
                new ObjectParameter("inv_articulo", inv_articulo) :
                new ObjectParameter("inv_articulo", typeof(int));
    
            var inv_descontar_cantidadParameter = inv_descontar_cantidad.HasValue ?
                new ObjectParameter("inv_descontar_cantidad", inv_descontar_cantidad) :
                new ObjectParameter("inv_descontar_cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInventarioSalida", inv_articuloParameter, inv_descontar_cantidadParameter);
        }
    
        public virtual int spEliminarUsuario(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarUsuario", id_usuarioParameter);
        }
    
        public virtual ObjectResult<string> spAgregarUsuario(string usu_nombre, string usu_password, Nullable<int> usu_perfil)
        {
            var usu_nombreParameter = usu_nombre != null ?
                new ObjectParameter("usu_nombre", usu_nombre) :
                new ObjectParameter("usu_nombre", typeof(string));
    
            var usu_passwordParameter = usu_password != null ?
                new ObjectParameter("usu_password", usu_password) :
                new ObjectParameter("usu_password", typeof(string));
    
            var usu_perfilParameter = usu_perfil.HasValue ?
                new ObjectParameter("usu_perfil", usu_perfil) :
                new ObjectParameter("usu_perfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spAgregarUsuario", usu_nombreParameter, usu_passwordParameter, usu_perfilParameter);
        }
    
        public virtual int spEditarUsuario(Nullable<int> id_usuario, string usu_nombre, string usu_password, Nullable<int> usu_perfil)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var usu_nombreParameter = usu_nombre != null ?
                new ObjectParameter("usu_nombre", usu_nombre) :
                new ObjectParameter("usu_nombre", typeof(string));
    
            var usu_passwordParameter = usu_password != null ?
                new ObjectParameter("usu_password", usu_password) :
                new ObjectParameter("usu_password", typeof(string));
    
            var usu_perfilParameter = usu_perfil.HasValue ?
                new ObjectParameter("usu_perfil", usu_perfil) :
                new ObjectParameter("usu_perfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditarUsuario", id_usuarioParameter, usu_nombreParameter, usu_passwordParameter, usu_perfilParameter);
        }
    
        public virtual int spEliminarArticulo(Nullable<int> id_articulo)
        {
            var id_articuloParameter = id_articulo.HasValue ?
                new ObjectParameter("id_articulo", id_articulo) :
                new ObjectParameter("id_articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarArticulo", id_articuloParameter);
        }
    
        public virtual int spAgregarArticulo(string art_nombre, string art_descripcion, Nullable<decimal> art_precio_uni, Nullable<decimal> art_precio_mayor_1, Nullable<decimal> art_precio_mayor_2)
        {
            var art_nombreParameter = art_nombre != null ?
                new ObjectParameter("art_nombre", art_nombre) :
                new ObjectParameter("art_nombre", typeof(string));
    
            var art_descripcionParameter = art_descripcion != null ?
                new ObjectParameter("art_descripcion", art_descripcion) :
                new ObjectParameter("art_descripcion", typeof(string));
    
            var art_precio_uniParameter = art_precio_uni.HasValue ?
                new ObjectParameter("art_precio_uni", art_precio_uni) :
                new ObjectParameter("art_precio_uni", typeof(decimal));
    
            var art_precio_mayor_1Parameter = art_precio_mayor_1.HasValue ?
                new ObjectParameter("art_precio_mayor_1", art_precio_mayor_1) :
                new ObjectParameter("art_precio_mayor_1", typeof(decimal));
    
            var art_precio_mayor_2Parameter = art_precio_mayor_2.HasValue ?
                new ObjectParameter("art_precio_mayor_2", art_precio_mayor_2) :
                new ObjectParameter("art_precio_mayor_2", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarArticulo", art_nombreParameter, art_descripcionParameter, art_precio_uniParameter, art_precio_mayor_1Parameter, art_precio_mayor_2Parameter);
        }
    
        public virtual int spEditarArticulo(Nullable<int> id_articulo, string art_nombre, string art_descripcion, Nullable<decimal> art_precio_uni, Nullable<decimal> art_precio_mayor_1, Nullable<decimal> art_precio_mayor_2)
        {
            var id_articuloParameter = id_articulo.HasValue ?
                new ObjectParameter("id_articulo", id_articulo) :
                new ObjectParameter("id_articulo", typeof(int));
    
            var art_nombreParameter = art_nombre != null ?
                new ObjectParameter("art_nombre", art_nombre) :
                new ObjectParameter("art_nombre", typeof(string));
    
            var art_descripcionParameter = art_descripcion != null ?
                new ObjectParameter("art_descripcion", art_descripcion) :
                new ObjectParameter("art_descripcion", typeof(string));
    
            var art_precio_uniParameter = art_precio_uni.HasValue ?
                new ObjectParameter("art_precio_uni", art_precio_uni) :
                new ObjectParameter("art_precio_uni", typeof(decimal));
    
            var art_precio_mayor_1Parameter = art_precio_mayor_1.HasValue ?
                new ObjectParameter("art_precio_mayor_1", art_precio_mayor_1) :
                new ObjectParameter("art_precio_mayor_1", typeof(decimal));
    
            var art_precio_mayor_2Parameter = art_precio_mayor_2.HasValue ?
                new ObjectParameter("art_precio_mayor_2", art_precio_mayor_2) :
                new ObjectParameter("art_precio_mayor_2", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditarArticulo", id_articuloParameter, art_nombreParameter, art_descripcionParameter, art_precio_uniParameter, art_precio_mayor_1Parameter, art_precio_mayor_2Parameter);
        }
    
        public virtual int spAgregarEntrada(Nullable<int> ent_usuario, Nullable<int> ent_cantidad, Nullable<int> ent_articulo)
        {
            var ent_usuarioParameter = ent_usuario.HasValue ?
                new ObjectParameter("ent_usuario", ent_usuario) :
                new ObjectParameter("ent_usuario", typeof(int));
    
            var ent_cantidadParameter = ent_cantidad.HasValue ?
                new ObjectParameter("ent_cantidad", ent_cantidad) :
                new ObjectParameter("ent_cantidad", typeof(int));
    
            var ent_articuloParameter = ent_articulo.HasValue ?
                new ObjectParameter("ent_articulo", ent_articulo) :
                new ObjectParameter("ent_articulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarEntrada", ent_usuarioParameter, ent_cantidadParameter, ent_articuloParameter);
        }
    }
}
