//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_de_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreda
    {
        public int id_entrada { get; set; }
        public Nullable<System.DateTime> ent_fecha { get; set; }
        public Nullable<int> ent_usuario { get; set; }
        public Nullable<int> ent_cantidad { get; set; }
        public Nullable<int> ent_articulo { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
