//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_de_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwmostrararticulo
    {
        public int id_articulo { get; set; }
        public string art_nombre { get; set; }
        public Nullable<decimal> art_precio_uni { get; set; }
        public Nullable<decimal> art_precio_mayor_1 { get; set; }
        public Nullable<decimal> art_precio_mayor_2 { get; set; }
    }
}
